version: "2.3"
services:
  app:
    image: rayson/kube-nextcloud:latest
    build:
      context: images/kube-nextcloud
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_HOST=db:5432
    volumes:
      - nextcloud-data:/var/www/html/data
      - nextcloud-config:/var/www/html/config
      - nextcloud-custom_apps:/var/www/html/custom_apps
    ports:
      - 8080:8080/tcp
  db:
    image: docker.io/centos/postgresql-96-centos7:latest
    volumes:
      - db:/var/lib/pgsql/data
    environment:
      - POSTGRESQL_USER=nextcloud
      - POSTGRESQL_PASSWORD=changeme
      - POSTGRESQL_DATABASE=nextcloud
volumes:
  nextcloud-data:
  nextcloud-config:
  nextcloud-custom_apps:
  db:

