kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-nextcloud-data
  labels:
    app: kube-nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
