apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-nextcloud-config
  labels:
    app: kube-nextcloud
data:
  custom.config.php: |
    <?php
    $CONFIG = array (
      'maintenance' => false,
      //'trusted_domains' =>
      //  array (
      //    0 => 'kube-nextcloud:80',
      //  ),
      //'tempdirectory' => '/tmp/nextcloudtemp',
      'theme' => '',
      'filesystem_check_changes' => 0,
      'trusted_proxies' => array(
        0 => '192.168.0.0/16',
        0 => '172.16.0.0/12',
        0 => '10.0.0.0/8',
      ),
    );
